// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// em_ito
std::vector<double> em_ito(double x0, double t, double drift, double volat, unsigned int n);
RcppExport SEXP _sdes_em_ito(SEXP x0SEXP, SEXP tSEXP, SEXP driftSEXP, SEXP volatSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type drift(driftSEXP);
    Rcpp::traits::input_parameter< double >::type volat(volatSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(em_ito(x0, t, drift, volat, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sdes_em_ito", (DL_FUNC) &_sdes_em_ito, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_sdes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
