# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Solve a constant-coefficient SDE for Ito diffusion
#'
#' @param x0 initial value
#' @param t the time period to solver over
#' @param drift the drift-rate
#' @param volat the volatility coefficient
#' @param n number of variates in time-discretization
#'
#' @description {Solve the SDE for a constant-coefficient Ito diffusion.}
#' @return numeric vector
em_ito <- function(x0, t, drift, volat, n) {
    .Call(`_sdes_em_ito`, x0, t, drift, volat, n)
}

